### ISSUE TITLE
Request for breathing session dialog activation options

### ISSUE THREAD

**Issue by milkmiruku** [mindfulness-at-the-computer/mindfulness-at-the-computer#310]
The greenbox method is fair in general, but too small for some. Could it be possible to have options of alternative methods of activating the in breath? Like mouse hover over the whole breath dialog, or keyboard press?

**Comment by SunyataZero** [comment]
@milkmiruku We now have support for using the shift key (left or right), but it's not documented

We have been thinking about allowing different breathing visualizations, actually i'm experimenting with a different approach now

The simplest solution is maybe to just make the breathing dialog a bit bigger, would this work?

**Comment by milkmiruku** [comment]
Shift is handy for now, thanks! The problem for me is that it needs the breath dialog to be active, which is kinda natural, but I ultimately personally prefer the advantages of using the keyboard more than mouse, especially with a tiling window manager, and for that my feature request would be of some command-line method to telling the app that my breath direction has changed so I could then bind a hotkey in my i3 config to trigger that.

(Minor UI/dialog note: while I can use the i3 hotkey to cycle through floating windows to select the breathing dialog, the dialog window type is of a different type to, say, the small reminder dialog of Workrave, in that the latter is given a border by i3, and the MatC one does not, so I cannot tell if the MatC dialog is selected when it is.)

But I'm not a hardcore mouse hater, I still use it a fair bit. I would imagine a larger breath dialog would help some, i.e. I think it's current size could be an accessibility problem to some with visibility/movement issues, and would recommend having an option for having a larger one, though I would actually prefer to have a smaller dialog than it is now that I could mouse over any part of the dialog for the breath in.

(In general, I prefer a nondual approach in various manners. What I'm ultimately looking for is an app that a) touches on timed/paced breathing sessions and b) can be continual. I know from Gitter history that there is a preference against being 'told' how to breathe compared to present breathing, but, as per my chat on Gitter, I think a) mindfulness also has a remembering [in the moment] aspect in it, and sometimes it seems one needs an ambient reminder on breath technique that can be used for a time, and b) the app already touches on right effort through actions so what's wrong with a bit of concentration on some tranquillity for a while or so. Bhikkhu Sujato was quite blunt in giving their [History of Mindfulness](http://santifm.org/santipada/wp-content/uploads/2012/08/A_History_of_Mindfulness_Bhikkhu_Sujato.pdf) the subtitle of "How insight worsted tranquillity in the Satipaṭṭhāna Sutta")

**Comment by SunyataZero** [comment]
> Shift is handy for now, thanks!

Alright, glad to hear this work for you! I will check our user documentation (not linked to at the moment so hard to find but will be used in the future) to see if we cover this. Or we could even include this in the intro wizard, what do you think?

> my feature request would be of some command-line method to telling the app that my breath direction has changed so I could then bind a hotkey in my i3 config to trigger that.

You mean changing from the shift key to another key for breathing in and out?

> (Minor UI/dialog note: while I can use the i3 hotkey to cycle through floating windows to select the breathing dialog, the dialog window type is of a different type to, say, the small reminder dialog of Workrave, in that the latter is given a border by i3, and the MatC one does not, so I cannot tell if the MatC dialog is selected when it is.)

We have been using different window "hints" for our windows, Qt takes hints for what type of window it should be, it's called hints because it can vary between different platforms. On LXDE when i alt+tab through the windows i can see a broad border around the (interactive) breathing dialog window as with the others

However the breathing notification (lower right) is not shown at all in the alt+tab list (this is by design)

> I would actually prefer to have a smaller dialog than it is now that I could mouse over any part of the dialog for the breath in.

Okay and breathing out as soon as the mouse cursor leaves the window/application as a whole?

> What I'm ultimately looking for is an app that a) touches on timed/paced breathing sessions and b) can be continual

I'm feeling confused, what does continual mean here? That there is a possibility to move to other breathing phrases automatically? (Right now this is possible by selecting a new breathing phrase in the combobox in the lower left of the breathing dialog)

> mindfulness also has a remembering [in the moment] aspect in it, and sometimes it seems one needs an ambient reminder on breath technique that can be used for a time

Interesting, i would like to bring this up with Marieke as she has years of experience in mindfulness practice. I don't want to do that now though because she is feeling overwhelemed by her work on chaning the the settings, so i'll just give my own view on this: Thich Nhat Hanh talks about allowing our breathing to be fast, he says that our breathing will naturally become more slow after a while and advises us not to force our breathing. This is interesting and i can see your point also so would like to continue the discussion if you are willing

**Comment by SunyataZero** [comment]
@milkmiruku I've been experimenting with a different approach for another application, what do you think?

![image](https://user-images.githubusercontent.com/10245688/40616593-f50e2374-628b-11e8-8160-b9d8bb7e2321.png)

This is a large version, but could easily be made smaller. The lower and upper areas expand as the user hovers over them (and the text follows at half speed, keeping the text in the center)
