### ISSUE TITLE
[XFCE] Left clicking icon in system tray does nothing

### ISSUE THREAD

**Issue by andy5995** [mindfulness-at-the-computer/mindfulness-at-the-computer#5]
When the program is minimized to the system tray, left-clicking the icon does nothing.

I can right click, and left-click on restore. Works great :)

I'm using XFCE 4.12 on Debian Linux 9

**Comment by SunyataZero** [comment]
Thank you for finding and reporting this issue, i use LXDE (Lubuntu) and on my desktop if i right click it will trigger a LXDE menu (unrelated to Mindfulness at the Computer), while left click will show the menu. (This is the same behavior as for redshift for example, but different systray application are behaving differently for me). I will look into this, thank you again for reporting

Kind Regards, Tord

**Comment by andy5995** [comment]
You're welcome.

I'm not sure if there's a "standard specification" on how an app should work in the system tray, to be honest.

Right now I have five icons in my system tray

When all these apps are minimized to the tray:
1. Left clicking on my IRC client restores
2. Left clicking on my RSS reader restores
3. Left clicking on pidgin IM restores
3. Left clicking the wifi icon brings up a list of networks
4. Left clicking pulse audio brings up a menu with different things I can do

I'll try redshift soon if that will help.

**Comment by SunyataZero** [comment]
The behavior i would like (for all platforms) is that the menu is shown on left click (and right click is ignored). Btw [transmission-gtk](https://transmissionbt.com/) also has the same behavior as redshift and matc does now

**Comment by andy5995** [comment]
>The behavior i would like (for all platforms) is that the menu is shown on left click (and right click is ignored). Btw transmission-gtk also has the same behavior as redshift and matc does now

Ok. I'll close this and create a ticket  for that.

**Comment by SunyataZero** [comment]
@andy5995 Have you tried redshift or transmission? I'm curios what they show on XFCE since i'm using the default in Qt (in other words i haven't chosen which button to click). It may be that XFCE switches the buttons in the menu when the buttons are not specified. This is actually my suspicion: that the buttons are switched and that this is the desired behavior for that platform. If that's the case i'd really like to keep it as it is. It may be possible to switch which buttons are used as in KeePassX (which uses Qt) for example, but looking at KeePassX i can see that the menu is not as well-integrated into the system tray as for MatC which i'd like to avoid. I'm a bit tired now so hope i don't come off as negative. Kind Regards, Tord

**Comment by andy5995** [comment]
Nope, not negative, you're fine, but I'll follow up later. :)

**Comment by andy5995** [comment]
I installed redshift!

When I left-click, I get a menu. When I right-click, I get the same menu.

**Comment by SunyataZero** [comment]
Thank you for testing this, i've now written this question on SO: https://stackoverflow.com/questions/46625306/xfce-and-qt-left-clicking-on-systray-does-nothing

**Comment by SunyataZero** [comment]
Many solutions have now been tried, the latest was to simply catch the activated signal for the menu icon and then manually emitting the activated signal
```
self.tray_icon.activated.emit(i_reason)
```
(this worked for XFCE since the function is entered even on left click), but that produced this error on MacOS for @mbed67 :
```
File "/Users/marieke/myprojects/mindfulness-at-the-computer/mc/gui/main_win.py", line 208 in on_systray_activated
...
Abort trap: 6
```

Because of this i don't know what to do about this issue, maybe we could call "super()" for the systray but then we would have to know the desktop environment [which doesn't seem to be possible to do](https://stackoverflow.com/questions/47022134/how-can-i-find-out-at-runtime-which-desktop-environment-that-a-qt-application) in a reliable way. For this reason and because it's possible to see the menu on XFCE (using right click) i've removed the catching of the activated signal and gone back to the default

**Comment by yigitsever** [comment]
Left clicking on system tray icon crashes the application for me:

```
INFO: ===== Starting Mindfulness at the Computer - 1.0.0-alpha.4 =====
INFO: Python version: 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0]
INFO: SQLite version: 3.21.0
INFO: PySQLite (Python module) version: 2.6.0
INFO: Qt version: 5.9.3
INFO: PyQt (Python module) version: 5.9.2
INFO: Mindfulness at the Computer - Application version: 1.0.0-alpha.4
INFO: Mindfulness at the Computer - Database schema version: 7
INFO: =====
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
INFO: ##### System Information #####
INFO: System tray available: Yes
INFO: System tray notifications supported: Yes
INFO: buildCpuArchitecture: x86_64
INFO: currentCpuArchitecture: x86_64
INFO: kernel type and version: linux 4.9.68-1-MANJARO
INFO: product name and version: Manjaro Linux
```
Then: 
```
DEBUG: ===== on_systray_activated entered =====
DEBUG: i_reason = 3
DEBUG: mouseButtons() = <PyQt5.QtCore.MouseButtons object at 0x7fe8a60a24a8>
DEBUG: ===== on_systray_activated entered =====
DEBUG: i_reason = 3
DEBUG: mouseButtons() = <PyQt5.QtCore.MouseButtons object at 0x7fe8a60a24a8>
DEBUG: ===== on_systray_activated entered =====
```
Which goes on for a while until a stack overflow

I'm on xfce as well

**Comment by SunyataZero** [comment]
Closed again because this is now documented in the docs/platform-differences.md file
